name = "playlist-transfer"
compatibility_date = "2026-05-15"
pages_build_output_dir = "apps/web/public"

[vars]
TRANSFER_API_URL = "https://playlist-transfer-api.onrender.com"

[[d1_databases]]
binding = "PLAYLIST_TRANSFER_DB"
database_name = "playlist-transfer"
database_id = "3d7f32b6-bf01-4ef9-acf1-0ead1ba60fa0"
